# Generated by Django 4.2.4 on 2023-09-24 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_add_related_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
