# Generated by Django 4.2.4 on 2023-09-24 02:42

from django.db import migrations
from django.apps import apps


def get_price(apps, schema_editor):
    OrderedProduct = apps.get_model('foodcartapp', 'OrderedProduct')
    ordered_products = OrderedProduct.objects.all().select_related('product')
    for ordered_product in ordered_products.iterator():
        price = ordered_product.product.price * ordered_product.quantity
        ordered_product.price = price
        ordered_product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_add_price_field'),
    ]

    operations = [
        migrations.RunPython(get_price)
    ]
