# Generated by Django 4.2.4 on 2023-10-07 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20230924_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AC', 'Заказ принят'), ('AS', 'Заказ собирается'), ('DE', 'Заказ у курьера'), ('CO', 'Заказ выполнен')], default='AC', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.DecimalValidator(decimal_places=2, max_digits=12)]),
        ),
    ]
