# Generated by Django 4.2.4 on 2023-10-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0043_order_status_alter_orderedproduct_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AC', 'Заказ принят'), ('AS', 'Заказ собирается'), ('DE', 'Заказ у курьера'), ('CO', 'Заказ выполнен')], db_index=True, default='AC', max_length=2),
        ),
    ]
