# Generated by Django 4.2.4 on 2023-10-07 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_add_datetime_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type_payment',
            field=models.CharField(choices=[('CALL', 'Не указан'), ('CARD', 'Карта'), ('CASH', 'Наличные'), ('PREPAY', 'Предоплата')], db_index=True, default='CALL', max_length=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 10, 7, 10, 53, 35, 328838, tzinfo=datetime.timezone.utc)),
        ),
    ]
