# Generated by Django 4.2.4 on 2023-11-11 09:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_restaurant_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 11, 11, 9, 16, 27, 943616, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, help_text='Ресторан в котором был собран заказ', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
    ]
