# Generated by Django 4.2.4 on 2023-11-11 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_alter_order_created_at_alter_order_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='call_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Звонок сделан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 11, 11, 9, 21, 54, 286693, tzinfo=datetime.timezone.utc), verbose_name='Заказ сделан'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Доставка выполнена'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('AC', 'Заказ принят'), ('AS', 'Заказ собирается'), ('DE', 'Заказ у курьера'), ('CO', 'Заказ выполнен')], db_index=True, default='AC', max_length=2, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_payment',
            field=models.CharField(choices=[('CALL', 'Не указан'), ('CARD', 'Карта'), ('CASH', 'Наличные'), ('PREPAY', 'Предоплата')], db_index=True, default='CALL', max_length=6, verbose_name='Тип оплаты'),
        ),
    ]
