# Generated by Django 4.2.4 on 2023-11-15 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0051_alter_order_call_at_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(unique=True)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=10)),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 11, 15, 9, 12, 26, 156506, tzinfo=datetime.timezone.utc), verbose_name='Заказ сделан'),
        ),
    ]
