# Generated by Django 4.2.4 on 2023-11-15 10:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0052_geodata_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodata',
            name='lat',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='lng',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 11, 15, 10, 16, 4, 620159, tzinfo=datetime.timezone.utc), verbose_name='Заказ сделан'),
        ),
    ]
