# Generated by Django 4.2.4 on 2023-11-18 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0055_alter_geodata_updated_at_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='geodata',
            name='geolocate',
            field=models.TextField(blank=True, null=True, verbose_name='Геолокация'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 11, 18, 7, 57, 58, 339463, tzinfo=datetime.timezone.utc), verbose_name='Заказ сделан'),
        ),
    ]
