# Generated by Django 4.2.4 on 2023-11-18 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_geodata_geolocate_alter_order_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WrongGeoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(unique=True, verbose_name='Не корректный адрес')),
            ],
            options={
                'verbose_name': 'Не распознанные адреса',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2023, 11, 18, 8, 7, 21, 916369, tzinfo=datetime.timezone.utc), verbose_name='Заказ сделан'),
        ),
    ]
