# Generated by Django 4.2.7 on 2023-11-24 14:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_wronggeodata_alter_order_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wronggeodata',
            options={'verbose_name': 'Не распознанные адреса', 'verbose_name_plural': 'Не распознанные адреса'},
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Заказ сделан'),
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.DecimalValidator(decimal_places=2, max_digits=6)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderedproduct',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
